cluster:
  name: dev
  network:
    cidr: 192.168.110.0/24
    start_ip: 192.168.110.20
    gateway: 192.168.110.1
    dns: 192.168.110.1
    dns2: 1.1.1.1
  defaults:
    datastore: SSD01
    network_name: LAN
    folder: Production
    resource_pool: Resources
    timeout_minutes: 45
  node_types:
    controlplane:
      cpus: 4
      memory_mb: 8192
      disk_size_gb: 60
      talos_version: v1.12.4
      schematic_id: 903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    worker:
      cpus: 8
      memory_mb: 16384
      disk_size_gb: 100
      talos_version: v1.12.4
      schematic_id: 903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
  layout:
    - type: controlplane
      count: 3
      prefix: cp
    - type: worker
      count: 2
      prefix: wk
